version: "3.8"
services:
  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mongodb
  mongodb:
    image: mongo:7.0.5-rc0-jammy
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db
volumes:
  mongodb: